const constantErrors = {
    INCORRECT_PASSWORD : 'INCORRECT_PASSWORD',
    ACCOUNT_DOEN_NOT_EXISTS : 'ACCOUNT_DOEN_NOT_EXISTS',
    EMAIL_ALREADY_EXISTS : 'EMAIL_ALREADY_EXISTS',
    INVALID_REFRESH_TOKEN:'INVALID_REFRESH_TOKEN',
    
    NO_TASK_FOUND:'NO_TASK_FOUND',
    TASK_NOT_FOUND : 'TASK_NOT_FOUND',
    NO_FIELD_TO_UPDATE : 'NO_FIELD_TO_UPDATE',
    NOTIFICATION_NOT_FOUND:'NOTIFICATION_NOT_FOUND',

    UNAUTHORIZED_ACCESS : 'UNAUTHORIZED_ACCESS',
    SESSION_EXPIRED : 'SESSION_EXPIRED',
};

module.exports = constantErrors;