name: Prod API Deployment

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setting Environment Variables
      run: |
        ############### SETTING ENV FILE STARTS ######################################################
        FILE_NAME=".env"
        echo "TZ='Asia/Kolkata'" > $FILE_NAME
        echo "PORT=${{vars.LISTEN_PORT}}" >> $FILE_NAME
        echo "REFRESH_TOKEN_EXPIRY=${{vars.REFRESH_TOKEN_EXPIRY}}" >> $FILE_NAME
        echo "ACCESS_TOKEN_EXPIRY=${{vars.ACCESS_TOKEN_EXPIRY}}" >> $FILE_NAME

        echo "MONGO_DB_STRING=${{secrets.MONGO_DB_STRING}}" >> $FILE_NAME
        echo "JWT_PRIVATE_KEY=${{secrets.JWT_PRIVATE_KEY}}" >> $FILE_NAME
        
        ############### SETTING ENV FILE END ######################################################

    - name: SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY_CONTENT" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} echo "Connection established"
      env:
        PRIVATE_KEY_CONTENT: ${{secrets.SSH_KEY}}
      
    - name: Coping Files to Server
      run: |
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo rm -rf task-scheduler-backend && sudo mkdir -p task-scheduler-backend"
        sudo tar --exclude=".git*" --exclude="id_rsa" --exclude="*.yml" -cf - . | ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "sudo tar -C task-scheduler-backend -xf -"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker build --rm -t task-scheduler-backend-image task-scheduler-backend/"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker stop task-scheduler-backend || true"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker run  -p 3000:3000 --rm --name task-scheduler-backend -dt task-scheduler-backend-image"
        ssh ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} "docker system prune -f"